language: python
python:
  - 2.7

install:
  - pip install .
  - pip install -r requirements.txt
  - pip install coveralls

script:
  - coverage run setup.py test
  - coverage report -m

after_script:
  - coveralls --verbose