language: python
python:
  - 2.7

install:
  - pip install .
  - pip install -r requirements.txt
  - pip install coveralls

script:
  - nosetests
  - coverage report

after_script:
  - coveralls --verbose